# Generated by Django 6.1 on 2026-08-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanha',
            name='locais',
            field=models.ManyToManyField(to='principal.localvacinacao'),
        ),
        migrations.AddField(
            model_name='campanha',
            name='vacinas',
            field=models.ManyToManyField(to='principal.vacina'),
        ),
    ]
