# Generated by Django 6.1 on 2026-09-01 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_campanha_locais_campanha_vacinas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campanha',
            options={'ordering': ['nome'], 'verbose_name': 'Campanha', 'verbose_name_plural': 'Campanhas'},
        ),
        migrations.AlterModelOptions(
            name='localvacinacao',
            options={'ordering': ['nome'], 'verbose_name': 'Local de Vacinação', 'verbose_name_plural': 'Locais de Vacinação'},
        ),
        migrations.AlterModelOptions(
            name='vacina',
            options={'ordering': ['nome'], 'verbose_name': 'Vacina', 'verbose_name_plural': 'Vacinas'},
        ),
    ]
